__// last generated: 11.05.2025 21:09:52 +0200__ +
 +

== Python Functions and Classes

[subs="+macros"]
----
└── link:.[.]
    └── link:app[app]
        ├── link:app/helpers[helpers]
        │   ├── link:app/helpers/dir_tree.py[dir_tree.py] (<<src-0,details>>)
        │   ├── link:app/helpers/misc.py[misc.py] (<<src-1,details>>)
        │   └── link:app/helpers/render.py[render.py] (<<src-2,details>>)
        ├── link:app/sv_parser.py[sv_parser.py] (<<src-3,details>>)
        ├── link:app/py_parser.py[py_parser.py] (<<src-4,details>>)
        └── link:app/docs_parser.py[docs_parser.py] (<<src-5,details>>)
----


== [[src-0]] dir_tree.py

=== Functions

* *make_dir_tree*
+
[source]
----
converts abstract syntax tree to tree-like output

Parameters
----------
combined_ast: dict
              abstract syntax tree generated by Parser class
last:         bool, default=True
              used in recursion; set True if node is last node in a branch
header:       str, default=""
              used in recursion; contains tree symbols preceeding the current line of the output
lines:        list of str, optional
              used in recursion; holds the previously generated lines of output
adoc_links:   bool, default=False
              if True, adds adoc compatible relative links to each file in the tree
adoc_anchors: bool, default=False
              if True, adds adoc compatible links to anchors for use in the same adoc document

Returns
-------
str
    tree-like output generated from ast
----
+
[source,python]
----
def make_dir_tree(
        combined_ast: dict,
        last: bool=True,
        header: str='',
        lines: Optional[list[str]]=None,
        adoc_links: bool=False,
        adoc_anchors: bool=False
    ) -> str:
----
+
(link:app/helpers/dir_tree.py#L8-L75[jump to definition]) +
 +

* *add_file_idx*
+
[source]
----
recursively goes through node and adds unique idx to each file

Parameters
----------
node: dict
      (part of) combined abstract syntax tree (depending on current recursion step)

Returns
-------
dict
    new (part of) combined abstract syntax tree (depending on current recursion step)
----
+
[source,python]
----
def add_file_idx(node: dict) -> dict:
----
+
(link:app/helpers/dir_tree.py#L80-L115[jump to definition]) +
 +

* *prune_ast*
+
[source]
----
recursively prunes directories that do not contain any files (directly or indirectly) or don't match any of the include_filters

Parameters
----------
node:            dict
                 (part of) combined abstract syntax tree to process
include_filters: list of str, optional
                 list of include filters (regex) specifying which files/paths to include in result

Returns
-------
dict or None
    remaining (part of) combined abstract syntax tree or None if pruning
----
+
[source,python]
----
def prune_ast(node: dict, include_filters: Optional[list[str]]=None) -> dict | None:
----
+
(link:app/helpers/dir_tree.py#L118-L161[jump to definition]) +
 +


== [[src-1]] misc.py

=== Functions

* *matches_any_regex*
+
[source]
----
checks if any of the regex filters return a match for provided data

Parameters
----------
data:          str
               data to check for matches
regex_filters: list of str, optional
               list of regex filters (str)
Returns
-------
bool
    True if any match was found, False otherwise or if no filters provided
----
+
[source,python]
----
def matches_any_regex(data: str, regex_filters: Optional[list[str]]=None) -> bool:
----
+
(link:app/helpers/misc.py#L7-L24[jump to definition]) +
 +


== [[src-2]] render.py

=== Functions

* *render_file_template*
+
[source]
----
renders provided jinja2 file template with given data

Parameters
----------
templates_dir: str
               search path for jinja2 templates
template:      str
               filename of template
data:          dict
               template variables
outfile:       str
               filename and path of output
----
+
[source,python]
----
def render_file_template(templates_dir: str, template: str, data: dict, outfile: str) -> None:
----
+
(link:app/helpers/render.py#L8-L35[jump to definition]) +
 +


== [[src-3]] sv_parser.py


=== Classes

* *SystemVerilogParser*
+
[red]#*FIXME*#: Add documentation!
+
[source,python]
----
class SystemVerilogParser(Parser):
----
+
(link:app/sv_parser.py#L9-L243[jump to definition]) +
 +
+
*Methods*

** *target_file_extensions*
+
[red]#*FIXME*#: Add documentation!
+
[source,python]
----
@property
def target_file_extensions(self):
----
+
(link:app/sv_parser.py#L11-L13[jump to definition]) +
 +


** *parse_file*
+
[source]
----
parses specified systemverilog file for modules and docs_description comments

Parameters
----------
full_path: str
           absolute path to target file

Returns
-------
dict
    module definitions and docs_description comments of parsed file
----
+
[source,python]
----
def parse_file(self, full_path: str) -> dict:
----
+
(link:app/sv_parser.py#L16-L106[jump to definition]) +
 +


** *make_docs*
+
[source]
----
parses systemverilog files for modules and docs_description comments and generates AsciiDoc documentation from them

inline comments or comment blocks starting with keyword 'docs_description' are included in the documentation
----
+
[source,python]
----
def make_docs(self):
----
+
(link:app/sv_parser.py#L109-L126[jump to definition]) +
 +


** *create_arg_parser*
+
[red]#*FIXME*#: Add documentation!
+
[source,python]
----
def create_arg_parser(self):
----
+
(link:app/sv_parser.py#L129-L132[jump to definition]) +
 +


** *combined_ast_to_list_of_files*
+
[source]
----
recursively converts combined abstract syntaxt tree to flattened list of files

Parameters
----------
node:      dict
           (part of) combined abstract syntax tree to process
flattened: list, optional
           holds new contents already assembled by previous recursion steps

Returns
-------
list
    flattened list of files
----
+
[source,python]
----
def combined_ast_to_list_of_files(self, combined_ast: dict, flattened: Optional[list]=None) -> list:
----
+
(link:app/sv_parser.py#L135-L172[jump to definition]) +
 +


** *make_instance*
+
[source]
----
converts extracted module info to instance template str

Parameters
----------
module: dict
        module data

Returns
-------
str
    instance template (str) of module
----
+
[source,python]
----
def make_instance(self, module: dict) -> str:
----
+
(link:app/sv_parser.py#L175-L243[jump to definition]) +
 +

== [[src-4]] py_parser.py


=== Classes

* *PythonParser*
+
[red]#*FIXME*#: Add documentation!
+
[source,python]
----
class PythonParser(Parser):
----
+
(link:app/py_parser.py#L9-L198[jump to definition]) +
 +
+
*Methods*

** *target_file_extensions*
+
[red]#*FIXME*#: Add documentation!
+
[source,python]
----
@property
def target_file_extensions(self):
----
+
(link:app/py_parser.py#L11-L13[jump to definition]) +
 +


** *parse_file*
+
[source]
----
parses specified python file for signatures and docstrings of classes and functions

Parameters
----------
full_path: str
           absolute path to target file

Returns
-------
dict
    signatures and docstrings of parsed functions and classes
----
+
[source,python]
----
def parse_file(self, full_path: str) -> dict:
----
+
(link:app/py_parser.py#L16-L89[jump to definition]) +
 +


** *create_arg_parser*
+
[red]#*FIXME*#: Add documentation!
+
[source,python]
----
def create_arg_parser(self):
----
+
(link:app/py_parser.py#L138-L141[jump to definition]) +
 +


** *combined_ast_to_list_of_files*
+
[source]
----
recursively converts combined abstract syntaxt tree to flattened list of files

Parameters
----------
node:      dict
           (part of) combined abstract syntax tree to process
flattened: list, optional
           holds new contents already assembled by previous recursion steps

Returns
-------
list
    flattened list of files
----
+
[source,python]
----
def combined_ast_to_list_of_files(self, combined_ast: dict, flattened: Optional[list]=None) -> list:
----
+
(link:app/py_parser.py#L144-L198[jump to definition]) +
 +

== [[src-5]] docs_parser.py


=== Classes

* *Parser*
+
[red]#*FIXME*#: Add documentation!
+
[source,python]
----
class Parser(ABC):
----
+
(link:app/docs_parser.py#L11-L154[jump to definition]) +
 +
+
*Methods*

** *target_file_extensions*
+
[source]
----
subclasses must specify list of file extensions they can parse
----
+
[source,python]
----
@property
@abstractmethod
def target_file_extensions(self):
----
+
(link:app/docs_parser.py#L25-L27[jump to definition]) +
 +


** *parse_file*
+
[source]
----
subclasses must implement parse_file method to parse a targeted file
----
+
[source,python]
----
@abstractmethod
def parse_file(self, full_path):
----
+
(link:app/docs_parser.py#L31-L33[jump to definition]) +
 +


** *make_docs*
+
[source]
----
subclasses must implement make_docs method with all steps required to generate AsciiDoc output
----
+
[source,python]
----
@abstractmethod
def make_docs(self):
----
+
(link:app/docs_parser.py#L37-L39[jump to definition]) +
 +


** *create_arg_parser*
+
[red]#*FIXME*#: Add documentation!
+
[source,python]
----
def create_arg_parser(self):
----
+
(link:app/docs_parser.py#L42-L58[jump to definition]) +
 +


** *get_combined_ast*
+
[source]
----
gets combined abstract syntax tree including directory structure for all found files
----
+
[source,python]
----
def get_combined_ast(self):
----
+
(link:app/docs_parser.py#L61-L80[jump to definition]) +
 +


** *render_file_template*
+
[red]#*FIXME*#: Add documentation!
+
[source,python]
----
def render_file_template(self, template_dir: str, template: str, data: dict) -> None:
----
+
(link:app/docs_parser.py#L149-L150[jump to definition]) +
 +


** *make_dir_tree*
+
[red]#*FIXME*#: Add documentation!
+
[source,python]
----
def make_dir_tree(self, combined_ast: dict) -> str:
----
+
(link:app/docs_parser.py#L153-L154[jump to definition]) +
 +

